name: shot_hdr
description: "A HDR screen capture tool for Windows, with planned macOS and Linux support."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core dependencies
  flutter_rust_bridge: ^2.11.1
  rust_lib_shot_hdr:
    path: rust_builder
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  # UI
  fluent_ui: ^4.9.2
  # Platform Tools (Windows specific, but dependencies are loaded anyway)
  window_manager: ^0.4.3
  tray_manager: ^0.2.3
  flutter_acrylic: ^1.1.4
  file_picker: ^8.1.6
  hotkey_manager: ^0.2.3
  super_clipboard: ^0.9.1
  uuid: ^4.5.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^12.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.9
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/